### ISSUE TITLE
Support for 6 month + vaccine products

### ISSUE THREAD

**Issue by dhcole** [usdigitalresponse/univaf#710]
We're hoping to see approval for new vaccine products, "Modern 6 month - 5 year", and a "Pfizer 6 month - 4 year". Is the a code we should look for for these coming from univaf sites? I believe we have an unused `pfizer_age_2_4` that may be repurposed.

**Comment by Mr0grog** [comment]
We can also rename this to `pfizer_age_0_4` real quick if that would be better.

Otherwise, we’re on it! For sources that use CVX codes (some SMART Scheduling Links sources, but not all) or NDC codes (the CDC), this should just work. For all the others (e.g. Albertsons chains, Rite Aid), we’ve got alerts for whenever we encounter a new vaccine name that should help us get these hooked up as soon as they start showing up in source data. 👍

**Comment by Mr0grog** [comment]
Will also add a `moderna_age_0_5` for the corresponding Moderna vaccine, which it looks like was also approved.

**Comment by Mr0grog** [comment]
Just to clarify, @dhcole, I’d like to rename it to `pfizer_age_0_4`, but want to make sure you aren’t already expecting/depending on the old name first. So let me know if that’s ok, please!

**Comment by dhcole** [comment]
Yes renaming is fine with us. Thanks @Mr0grog

**Comment by Mr0grog** [comment]
Alright, I renamed `pfizer_age_2_4` to `pfizer_age_0_4` and did a bunch of other cleanup and screw-tightening on vaccine types over in #714.

So the vaccine products you should expect to see in UNIVAF in the future are:
- `astra_zeneca`
- `jj`
- `moderna`
- `moderna_age_6_11`
- `moderna_age_0_5`
- `novavax`
- `pfizer`
- `pfizer_age_5_11`
- `pfizer_age_0_4`
- `sanofi` (not actually approved for use in the US yet)

I think we’ve done everything that can reasonably done in advance here, so I’m going to close this issue. Thanks for raising it, @dhcole!
