### ISSUE TITLE
Accessing minimum age metadata

### ISSUE THREAD

**Issue by dhcole** [usdigitalresponse/univaf#732]
Pharmacies may receive a vaccine product for young children (6mo+) but only be authorized to administer it to individuals 3 year+. Vaccines.gov seems to have this metadata represented by a `minimum_age` attribute: https://api.us.castlighthealth.com/vaccine-finder/v1/provider-locations/97650e43-14be-4275-bcaf-ca28aceba3da?inventoryCategory=covid

Having access to this attribute in the univaf feed would enable us to show users which sites are actually able to serve 6m-2y, vs which can only serve 3y+.

Would it be possible to include a `minimum_age` attribute on providers, where available?

**Comment by Mr0grog** [comment]
So it looks like they’ve also recently added this to their open data as well, but I’m working to understand a few things:

- There’s `minimum_age_months` (defined as “Minimum age for vaccinations at this location if <1 year or non-whole number”) and `minimum_age_years` (defined as “Minimum age for vaccinations at this location >1 year if minimum age is a whole number.”), but these are sometimes in conflict. (At first glance, it seems like vaccines.gov shows whichever is higher, but I also wouldn’t be surprised if the wrong thing is happening here somehow.)

- It seems like this is about the location and never about a particular vaccine. Do you know from any of your public health contacts if that’s correct?

**Comment by brendanbabb** [comment]
I was on a State of Alaska Health Dept. call yesterday, and a doctor indicated that via a rule, pharmacists are allowed to administer vaccines to 3 year olds and above, but younger than that and you need a clinician who can administer to 18 months and above. It would have to be researched but my understanding is that it depends if there is a clinician physically at a given pharmacy location.

This article mentions the 3 year old limit and the gov. document: https://www.nbcnews.com/health/health-news/covid-vaccines-children-under-5-rcna34107

HHS document:
https://www.hhs.gov/sites/default/files/third-amendment-declaration.pdf

**Comment by Mr0grog** [comment]
Great, thanks!

I was digging into situations where the two are in conflict and realized that what vaccines.gov does is only look at the minimum age in years. If it’s greater than 0, it shows that, otherwise it just says “Call for provider's age policies.”

We can put whatever vaccines.gov shows in the API and leave that part to you, or we can bake that logic in by only putting years in the API.

**Comment by Mr0grog** [comment]
First pass at actual code in #733. I’m going to let this stew for a couple hours so I can give it clear-eyed re-review later, but will get this data in sometime today.

**Comment by Mr0grog** [comment]
OK, this is about to land (sorry it took a little longer than expected). I’ve also [made some changes](https://github.com/usdigitalresponse/univaf/pull/733#issuecomment-1165945720):

- There’s only one field on the location instead of two: `minimum_age_months`. It simply states the age in months, whether that’s 6 (should be the earliest possible) or 144 (12 years). It may be null if we don’t have this info for a location yet.

- On the `availability` object, there’s a more useful shortcut: `location.availability.minimum_eligible_age_months`. This combines the location’s minimum age with the vaccine products on offer. For example, if the location’s minimum is 6 but the only vaccine offered is `pfizer`, this will be `144`. But if `pfizer_age_0_4` is offered, then it will be `6`. This may be null if we don’t have product info or a minimum age for the location.
