### ISSUE TITLE
CVS locations don't have products, which are available through vaccines.gov

### ISSUE THREAD

**Issue by dhcole** [usdigitalresponse/univaf#739]
Hi, I think I remember that the CVS API was not providing product information. In this example location, we see availability but no specific products: https://getmyvax.org/api/edge/locations/7d832aef-522f-4f35-94fd-e9783b3ce516

I noticed though that product information is available on vaccines.gov, and in that API response, we have the matching `vaccines_gov`. When searching that GUID on https://data.cdc.gov/Vaccinations/Vaccines-gov-COVID-19-vaccinating-provider-locatio/5jp2-pgaw/data, I see the vaccine product information.

Is it possible to merge the product info from vaccines.gov for locations like this?

**Comment by Mr0grog** [comment]
Hmmm, we should be pulling that info in (availability is the merged data from every source on a given location). Let me dig into it to see what’s happening.

**Comment by Mr0grog** [comment]
So it looks like this is happening because we discard data that is more than 48 hours old, and while we check the CDC data regularly, the last update from CVS was a little over 48 hours ago (specifically, at 2022-06-23 00:00:00Z). :\

https://github.com/usdigitalresponse/univaf/blob/93ade5b9c7908993bcc62b1a410addfdd4b83ea0/server/src/db.ts#L27-L32

I’ll bump this time up to one week, which should solve the issue.

**Comment by Mr0grog** [comment]
@dhcole looks like this is working now!

**Comment by dhcole** [comment]
Confirmed. Thanks for digging into and resolving this so quickly!
